version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    entrypoint: ./compose/local/php/docker-php-entrypoint-local
    environment:
      - "DB_HOST=db"
      - "DB_PORT=3306"
    depends_on:
      - db
  db:
    image: mariadb:10.4
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./compose/local/mariadb/data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: therootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel

volumes:
  db_data:
