version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    environment:
      - "DB_HOST=db"
      - "DB_PORT=3306"
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: my_mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./data/database.sql:/docker-entrypoint-initdb.d/import.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  db_data:
